plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

repositories {
    mavenCentral()
}

javafx {
    version = '25'
    modules = ['javafx.controls', 'javafx.fxml', 'javafx.media']
}

application {
    mainClass = 'Main'
    applicationDefaultJvmArgs = ['--enable-native-access=javafx.graphics,javafx.media']
}

jar {
    manifest {
        attributes 'Main-Class': 'Main'
    }
}

tasks.register('copyLibs', Copy) {
    from configurations.runtimeClasspath
    into layout.buildDirectory.dir('libs-all')
}
